Add support to specify a port
nezhar/wordpress-docker-compose pull request #86
Opened 2023-02-03 17:51 UTC by rafaelfrancisco-dev

Add support to specify a custom port using an environment variable. Useful for using a reverse proxy for example.

2023-02-12 12:57 UTC, nezhar requested changes

2023-02-12 12:57 UTC, nezhar commented on env.example
> +PORT=5999
This should default to `80`

2023-02-13 09:39 UTC, rafaelfrancisco-dev commented on env.example
> +PORT=5999
Fixed !

2023-02-13 09:59 UTC, nezhar approved these changes
Thanks :100:

2023-02-13 10:00 UTC, merged